### ISSUE TITLE
Where's is the daily CVD file? 

### ISSUE THREAD

**Issue by vepicurean** [Cisco-Talos/clamav-faq#161]
Where is the daily updated CVD file? It used to be easy to find on the main website and now I can't find it. 

Also the automated virus definitions process has not worked for weeks on QNAP.

**Comment by micahsnyder** [comment]
Please have a look at our mailing list. There are many conversations there on this issue: https://lists.archive.carbon60.com/clamav/users/81635

ClamAV versions older than 0.100 have been blocked from downloading database updates and must be upgraded. This is probably the issue you're seeing. We've been forced to make this change due to a large number of outdated ClamAV installs using a lot of bandwidth on our content deliver network.

Some users running ClamAV on QNAP and Synology devices have also reported issues using freshclam to update while clamd is running because it now requires more RAM than is available on older devices. It's not ideal but you can disable database load testing in freshclam.conf which may alleviate the issue. 

Our team isn't familiar with configuring ClamAV on QNAP so we can't help with specifics. If you need additional help updating ClamAV on your QNAP device, please contact QNAP for support with product updates.

**Comment by micahsnyder** [comment]
Regarding the daily updated CVD download location, please use FreshClam to keep your databases updated to try to minimize data usage.

If you maintain a private mirror for an organization, please use the new [cvdupdate tool](https://github.com/micahsnyder/cvdupdate).

**Comment by vepicurean** [comment]
I don't want to have to update ClamAV on the QNAPs manually. They have always updated the ClamAV definitions at the assigned time. 

But suddenly about two weeks ago on one of the QNAPs that all changed, and when I went looking for the CVD file (strictly as a work around until you all and QNAP go things straightened out) where I usually find it to do it manually, it's obvious someone purposefully changed something such that I can't find the daily CVD file anymore. 

The priority should be getting the automated virus definitions daily update via the QNAP working again. It calls out but every time now it comes back as "failed to update virus definitions".  So something was changed. It's been fine for many years. 

Can you all please open the ticket back up. Something is not right with ClamAV.

**Comment by finchy** [comment]
Qnap is running an old version of ClamAV that is no longer supported.  You must contact Qnap about this, we do not control the Qnap product

**Comment by vepicurean** [comment]
I see. Thanks for the information. I get on QNAP about it. I'm not surprised. They are not the most organized bunch technically.
