### ISSUE TITLE
LibClamAV Error: cli_realloc(): Attempt to allocate 190844928 bytes. Please report to https://bugzilla.clamav.net

### ISSUE THREAD

**Issue by thapaliyad** [Cisco-Talos/clamav-faq#163]
LibClamAV Error: cli_realloc(): Attempt to allocate 190844928 bytes. Please report to https://bugzilla.clamav.net

**Comment by micahsnyder** [comment]
Hi @thapaliyad , this isn't bugzilla.clamav.net 😉
But to be able to investigate this, we need some more context. Can you tell me what clamav version you're using? What type of file, and the size of the file, that you were scanning?

The error _sounds_ like something we fixed in clamav 0.103.2, here: https://github.com/Cisco-Talos/clamav-devel/commit/1a3b784e1954e00b6463000a817da0c5092296cd but I'd need more details to be sure.

**Comment by finchy** [comment]
Lets move this to bugzilla since this isn't an issue with the FAQ.

**Comment by thapaliyad** [comment]
I fully uninstalled - upgraded the system and re-installed. And it’s now
working.

Don’t know what happened. But the latest version resolved the issue.

Best,
Dhirendra
